apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: api
        image: vranystepan/workshop-app:eks
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  namespace: app2
spec:
  ingressClassName: nginx
  rules:
  - host: "app2.workshop.eks.rocks"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80
