apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store
  namespace: app3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: store
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3
  namespace: app3
spec:
  ingressClassName: nginx
  rules:
  - host: "app3.workshop.eks.rocks"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app3
            port:
              number: 80